/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view.AdminView;

import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.example.controller.UserController;
import org.example.domain.model.Role;
import org.example.domain.model.Status;
import org.example.domain.model.UserModel;

/**
 *
 * @author ADMIN
 */
public class UserManagerView extends javax.swing.JFrame {
        private UserController userController;

        /**
         * Creates new form UserManager
         */
        public UserManagerView() {
                initComponents();
                userController = new UserController();
                this.setLocationRelativeTo(null);
                this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                userTable = new javax.swing.JTable();
                btnAdd = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                txtName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtPassword = new javax.swing.JPasswordField();
                jLabel4 = new javax.swing.JLabel();
                txtFullname = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txtEmail = new javax.swing.JTextField();
                txtPhoneNumber = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txtAddress = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                txtRole = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                txtStatus = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                txtCreateat = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                txtUpdateat = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                userTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "ID", "UserName", "Password", "FullName", "Email", "PhoneNumber",
                                                "Address", "Role", "Status",
                                                "CreateAt", "UpDateAt"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class, java.lang.Object.class, java.lang.Object.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(userTable);
                if (userTable.getColumnModel().getColumnCount() > 0) {
                        userTable.getColumnModel().getColumn(0).setPreferredWidth(1);
                }

                btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jButton3.setText("Exit");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel2.setText("Name :");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Password :");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel4.setText("FullName:");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("Email :");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("PhoneNumber:");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel7.setText("Address :");

                jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel8.setText("Role :");

                jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel9.setText("Status :");

                jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel10.setText("CreateAt :");

                jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel11.setText("UpDateAt :");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnDelete)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnAdd)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton3)
                                                                .addGap(23, 23, 23))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(jLabel3))
                                                                                                .addGap(45, 45, 45)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(txtPassword,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                175,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtName,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                175,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                37,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(68, 68, 68)
                                                                                                                                                .addComponent(txtEmail,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                175,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addGap(48, 48, 48)
                                                                                                                                                .addComponent(txtFullname,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                176,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addGap(128, 128,
                                                                                                                                                                128)))
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(txtAddress,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                175,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addGap(43, 43, 43)
                                                                                                                                                .addComponent(txtPhoneNumber,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                175,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(138, 138,
                                                                                                                                138)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel11,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                65,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel8,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                37,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(37, 37, 37)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addComponent(txtUpdateat,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                175,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(txtRole,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                175,
                                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel10)
                                                                                                                                .addComponent(jLabel9))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                46,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(txtStatus,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                175,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(txtCreateat,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                175,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(5, 5, 5))
                                                .addComponent(jScrollPane1));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(txtStatus,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtEmail,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtPhoneNumber,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel6))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(txtCreateat,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(txtPassword,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(txtUpdateat,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(txtFullname,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(txtRole,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel8))
                                                                                                .addComponent(jLabel7,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                .addComponent(txtAddress,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                437, Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnDelete)
                                                                                .addComponent(btnAdd)
                                                                                .addComponent(jButton3))
                                                                .addGap(18, 18, 18)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void validateInput() throws IllegalAccessException {
                if (txtName.getText().trim().isEmpty() ||
                                Arrays.toString(txtPassword.getPassword()).isEmpty() ||
                                txtPhoneNumber.getText().trim().isEmpty() ||
                                txtAddress.getText().trim().isEmpty() ||
                                txtEmail.getText().trim().isEmpty() ||
                                txtRole.getText().trim().isEmpty() ||
                                txtStatus.getText().trim().isEmpty() ||
                                txtFullname.getText().trim().isEmpty() ||
                                txtCreateat.getText().trim().isEmpty() ||
                                txtUpdateat.getText().trim().isEmpty()) {
                        throw new IllegalAccessException(" All fields are required ");
                }

        }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
                this.setVisible(false);
                new AdminDashboardView().setVisible(true);
        }// GEN-LAST:event_jButton3ActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
                try {
                        validateInput();
                        UserModel productmodel;
                        productmodel = UserModel.builder()
                                        .username(txtName.getText().trim())
                                        .password(Arrays.toString(txtPassword.getPassword()))
                                        .fullname(txtFullname.getText().trim())
                                        .email(txtEmail.getText().trim())
                                        .phoneNumber(txtPhoneNumber.getText().trim())
                                        .address(txtAddress.getText().trim())
                                        .role(Role.valueOf(txtRole.getText().trim()))
                                        .status(Status.valueOf(txtStatus.getText().trim()))
                                        .createdAt(java.sql.Timestamp.valueOf(txtCreateat.getText().trim()))
                                        .updatedAt(java.sql.Timestamp.valueOf(txtUpdateat.getText().trim()))
                                        .build();

                        userController.insert(productmodel);
                        JOptionPane.showMessageDialog(this, " inserted successfully!");
                        clearFields();
                        refreshTable();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        "Error updating customer: " + e.getMessage(),
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_btnAddActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
                int selectedRow = userTable.getSelectedRow();

                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, " Please select a user to delete");
                        return;
                }

                int confirm = JOptionPane.showConfirmDialog(this,
                                "Are you sure you want to delete this user?",
                                "Confirm Delete",
                                JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        Long id = (Long) userTable.getValueAt(selectedRow, 0);
                        userController.delete(id);
                        JOptionPane.showMessageDialog(this, "user deleted successfully!");
                        clearFields();
                        refreshTable();
                } else {
                        clearFields();
                }

        }// GEN-LAST:event_btnDeleteActionPerformed

        private void clearFields() {
                txtName.setText("");
                txtPassword.setText("");
                txtAddress.setText("");
                txtFullname.setText("");
                txtEmail.setText("");
                txtPhoneNumber.setText("");
                txtRole.setText("");
                txtStatus.setText("");
                txtCreateat.setText("");
                txtUpdateat.setText("");
        }

        private void refreshTable() {
                try {
                        List<UserModel> customers = userController.getAll();
                        // Jable userTable = new JTable();Table userTable = new JTable();
                        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
                        model.setRowCount(0);

                        for (UserModel user : customers) {
                                model.addRow(new Object[] {
                                                user.getId(),
                                                user.getUsername(),
                                                user.getPassword(),
                                                user.getFullname(),
                                                user.getEmail(),
                                                user.getPhoneNumber(),
                                                user.getAddress(),
                                                user.getRole(),
                                                user.getStatus(),
                                                user.getCreatedAt(),
                                                user.getUpdatedAt(),

                                });
                        }
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,
                                        "Error refreshing table: " + e.getMessage(),
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(UserManagerView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(UserManagerView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(UserManagerView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(UserManagerView.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new UserManagerView().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField txtAddress;
        private javax.swing.JTextField txtCreateat;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtFullname;
        private javax.swing.JTextField txtName;
        private javax.swing.JPasswordField txtPassword;
        private javax.swing.JTextField txtPhoneNumber;
        private javax.swing.JTextField txtRole;
        private javax.swing.JTextField txtStatus;
        private javax.swing.JTextField txtUpdateat;
        private javax.swing.JTable userTable;
        // End of variables declaration//GEN-END:variables
}
